FROM python:3.6-alpine

EXPOSE 9090
WORKDIR /usr/src/app

#RUN apt-get update
#RUN DEBIAN_FRONTEND=noninteractive apt-get install -y -q curl net-tools

COPY ./code/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY ./code/ ./
CMD ["python", "user_greeting_service.py"]
